columns:
  
  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default

      settings:
        type: fields
        fields:
          showNavbar:
            label: Show navbar
            type: toggle
            text:
              - Hidden
              - Visible

          showFooter:
            label: Show footer
            type: toggle
            text:
              - Hidden
              - Visible

          footerText:
            label: Footer text
            type: writer
            inline: true

          showAnnouncementBar:
            label: Show announcement bar
            type: toggle
            text:
              - Hidden
              - Visible

          announcementTitle:
            label: Announcement title
            type: text

          announcementText:
            label: Announcement text
            type: writer
            inline: true